"""add knowledge graph entities and relationships

Revision ID: 3c594e4f6e5f
Revises: 6927e562daed
Create Date: 2026-08-16 11:30:10.843364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c594e4f6e5f'
down_revision: Union[str, Sequence[str], None] = '6927e562daed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_entity_name')
    )
    op.create_table('knowledge_relationships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['knowledge_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['knowledge_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate always flags ix_knowledge_chunks_*, ix_knowledge_sources_user_id,
    # and ix_memory_entries_* as "removed" - they were created via raw op.execute() SQL
    # in earlier migrations (HNSW vector indexes, GIN tsvector index), so SQLAlchemy's
    # model metadata never sees them and autogenerate assumes they're gone. They aren't -
    # the corresponding drop_index/create_index pairs are stripped from this migration.
    # Same story for checkpoints/checkpoint_writes/checkpoint_blobs/checkpoint_migrations -
    # those are LangGraph's own tables, created by AsyncPostgresSaver.setup()
    # (see app/core/checkpointer.py), not by anything in our SQLAlchemy models, so
    # autogenerate sees them as unmanaged and wants to drop them. They aren't ours to drop.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_relationships')
    op.drop_table('knowledge_entities')
    # ### end Alembic commands ###
