"""add pending_tool_confirmations table

Revision ID: 6927e562daed
Revises: d28cb4c1322d
Create Date: 2026-08-15 13:07:23.885879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6927e562daed'
down_revision: Union[str, Sequence[str], None] = 'd28cb4c1322d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_tool_confirmations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_message_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    # create_type=False - this enum type already exists (created by the llm_credentials
    # table's migration); CREATE TYPE again here would fail with DuplicateObject.
    sa.Column('provider', postgresql.ENUM('openai', 'anthropic', 'gemini', 'groq', name='llm_provider', create_type=False), nullable=False),
    sa.Column('tool_name', sa.String(length=256), nullable=False),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate always flags ix_knowledge_chunks_*, ix_knowledge_sources_user_id,
    # and ix_memory_entries_* as "removed" - they were created via raw op.execute() SQL
    # in earlier migrations (HNSW vector indexes, GIN tsvector index), so SQLAlchemy's
    # model metadata never sees them and autogenerate assumes they're gone. They aren't -
    # the corresponding drop_index/create_index pairs are stripped from this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_tool_confirmations')
    # ### end Alembic commands ###
