"""add conversation summary fields

Revision ID: 9d0abe53a312
Revises: ec48248f3fef
Create Date: 2026-08-25 14:54:22.320068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9d0abe53a312'
down_revision: Union[str, Sequence[str], None] = 'ec48248f3fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summarized_through_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'messages', ['summarized_through_message_id'], ['id'], ondelete='SET NULL')
    # NOTE: autogenerate always flags the checkpoint_* tables (owned by
    # LangGraph's AsyncPostgresSaver.setup(), not our SQLAlchemy models) and
    # several raw-SQL indexes (HNSW/GIN, created via op.execute() in earlier
    # migrations) as "removed", since SQLAlchemy's model metadata never sees
    # them. They aren't removed - the corresponding drop/create pairs are
    # stripped from this migration, same as d28cb4c1322d before it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_summarized_through_message_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'summarized_through_message_id')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
