"""add response_language to assistant_profiles

Revision ID: a6ee0d4e382a
Revises: 79e72a899035
Create Date: 2026-07-28 03:01:59.982727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ee0d4e382a'
down_revision: Union[str, Sequence[str], None] = '79e72a899035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_profiles', sa.Column('response_language', sa.String(length=64), server_default='English', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_profiles', 'response_language')
    # ### end Alembic commands ###
