"""add mcp_servers table

Revision ID: d28cb4c1322d
Revises: b2554d86847a
Create Date: 2026-08-09 05:30:45.638952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd28cb4c1322d'
down_revision: Union[str, Sequence[str], None] = 'b2554d86847a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('transport', sa.Enum('stdio', 'sse', name='mcp_transport'), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('encrypted_env', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate always flags ix_knowledge_chunks_*, ix_knowledge_sources_user_id,
    # and ix_memory_entries_* as "removed" - they were created via raw op.execute() SQL
    # in earlier migrations (HNSW vector indexes, GIN tsvector index), so SQLAlchemy's
    # model metadata never sees them and autogenerate assumes they're gone. They aren't -
    # the corresponding drop_index/create_index pairs are stripped from this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
