"""add scheduled_tasks table

Revision ID: ec48248f3fef
Revises: 3c594e4f6e5f
Create Date: 2026-08-21 19:52:04.942978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ec48248f3fef'
down_revision: Union[str, Sequence[str], None] = '3c594e4f6e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.Enum('daily', 'interval', name='schedule_type'), nullable=False),
    sa.Column('run_at_time', sa.Time(), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate always flags the checkpoint_* tables (owned by
    # LangGraph's AsyncPostgresSaver.setup(), not our SQLAlchemy models) and
    # several raw-SQL indexes (HNSW/GIN, created via op.execute() in earlier
    # migrations) as "removed", since SQLAlchemy's model metadata never sees
    # them. They aren't removed - the corresponding drop/create pairs are
    # stripped from this migration, same as d28cb4c1322d before it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
